In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [5]:
#create dataframes
df = pd.read_csv("test_scores.csv")
df

name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83
5   aamir    49  52
6  venkat    65  66
7   virat    35  30
8  arthur    66  68
9    paul    67  73

In [11]:
#make a model
reg = linear_model.LinearRegression()
#train the model
reg.fit(df[['math']], df.cs)

LinearRegression()

In [13]:
#get the coeficient
reg.coef_

array([1.01773624])

In [15]:
#get the y intercept
reg.intercept_

1.9152193111569318

In [17]:
#pickle is used to serialize python objects into a file
import pickle

In [24]:
#use pickle to save the model to a file.
#wb means write binary
with open("saved_model_pickle", "wb") as f:
    pickle.dump(reg, f)

In [23]:
#use model to predict output 
reg.predict([[88]])

array([91.47600824])

In [25]:
#use the saved model
#first open it in read mode
with open("saved_model_pickle", "rb") as f:
    mp = pickle.load(f)

In [28]:
#use the loaded model to make a prediction
mp.predict([[88]])

array([91.47600824])

In [33]:
#use joblib to save model to a file
import joblib

#save the model to a file
joblib.dump(reg, "model_saved_joblib")

['model_saved_joblib']

In [34]:
#use the saved model
saved_model = joblib.load("model_saved_joblib")

In [35]:
#use the saved model to make predictions
saved_model.predict([[80]])

array([83.33411834])